In [ ]:
import numpy as np
from math import comb
np.set_printoptions(suppress=True, precision=10)

In [ ]:
c, k, n = 5, 10, 10
# c = number of coins
# k = number of times a coin is chosen
# n = number of tosses by the coin
M = np.random.randint(2, size=(k, n))
print(M)
# 0 represents tails and 1 represents heads
# the information about which coin is chosen and tossed is unknown

[[0 0 1 1 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 1 1 0 0]
 [1 0 0 0 1 1 1 1 1 1]
 [0 1 1 0 1 0 0 0 0 1]
 [1 1 1 0 0 1 1 1 0 0]
 [1 0 1 0 1 1 0 0 0 1]
 [0 1 1 0 1 0 0 1 1 0]
 [0 0 1 1 0 1 1 1 1 0]
 [0 1 1 1 0 1 0 1 0 0]]


In [ ]:
Heads = np.array([np.sum(M[i]) for i in range(k)])
print(Heads)
# Heads consist of number of heads occured in the tosses of each time a coin is chosen

[4 3 3 7 4 6 5 5 6 5]


In [ ]:
Theta = np.random.rand(c)
print(Theta)
# Theta consists of initial bias of each of the coins

[0.3963798995 0.0005358744 0.203764281  0.9155402201 0.457756323 ]


In [ ]:
Pi = np.random.rand(c)
Pi /= np.sum(Pi)
print(Pi)
# Pi consists of the probability of each coin being chosen
# Pi = P(Coin)

[0.0550183007 0.1758957726 0.2395225968 0.2290640109 0.3004993191]


In [ ]:
Binom = np.zeros((k, c))
# Binom consists of probability of each event given a coin is chosen for each, calculated using Binomial Probability
# Binom = P(E | Coin)
Prob = np.zeros((k, c))
# Prob consists of probability of coin being chosen given the event has happened, calculated using Bayes Theorem
# Prob = P(Coin | E)
_Theta = np.zeros(c)
# _Theta consists of new bias of each coin calculated
move = True

In [ ]:
itr = 0
print(f'itr:{itr}->   Theta = {Theta}')
while move == True:
  itr += 1
  for i in range(k):
    h = Heads[i]
    Binom[i] = comb(n, h) * Theta**h * (1 - Theta)**(n - h)
    Prob[i] = Binom[i]*Pi / (np.sum(Binom[i]*Pi))
  for j in range(c):
    _Theta[j] = Heads@Binom.T[j] / (n*np.sum(Binom.T[j]))
  if np.array_equal(Theta, _Theta):
    move = False
  Theta = _Theta
  print(f'itr:{itr}->   Theta = {Theta}')

itr:0->   Theta = [0.3963798995 0.0005358744 0.203764281  0.9155402201 0.457756323 ]
itr:1->   Theta = [0.4397542135 0.3000939213 0.3567742677 0.668179187  0.4682097149]
itr:2->   Theta = [0.4598596472 0.3962026456 0.4215579285 0.5633237896 0.4730523263]
